---
title: "flex dashboards"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns #columns rather than rows, top to bottom 
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(ggplot2)
data("ny_noaa")
```


```{r initial data cleaning}
weather_data = 
  ny_noaa |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY")) |>
  mutate(tmin=as.numeric(tmin), tmax = as.numeric(tmax)) |>
  mutate(tmin = tmin / 10,
    tmax = tmax / 10) |>
  drop_na(tmin, tmax) |>
  select(name, id, everything()) |>
  filter(name%in% c("CentralPark_NY"))
```

Column {data-width=650} 
-----------------------------------------------------------------------

### Chart A: Scatter Plot

```{r}
weather_data |>
  filter(snow > 0) |>
  plot_ly(x=~tmax, y=~snow, color=~name,
      type = "scatter", mode="markers", alpha=0.5, colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B:Box Plot

```{r}
weather_data |>
   plot_ly(x=~name, y=~tmin, color=~name,
      type = "box", mode="markers", alpha=0.5, colors = "viridis")
```

### Chart C: Line plot

```{r}
weather_data |>
  filter(date >'2000-01-1') |>
  plot_ly(x=~date, y=~snow, color=~name,
      type = "scatter", mode="lines", alpha=0.5, colors = "viridis")
```
